# Generated by Django 4.2.17 on 2025-05-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0021_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='i',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='images',
        ),
    ]
